name = "Terratech Ceu"
author = "NotJustAnna et. al"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9263dd6a575b6e2f5fb413fddd4ada5162372f9d325fcc40113d90653c38b06f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
