name = "Terratech CEu - Baseline"
author = "NotJustAnna et. al"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9165c2223b0559539aed20e702764a1c589a8bd4f4bb5d7dcbf27d1196a69a6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
