name = "Terratech CEu"
author = "NotJustAnna et. al"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5ba6c704c25c3e49dc4839db3314a3b4cf2f5d5d3180f16303093cadfa3ee75"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
